In [1]:
#from dotenv import load_dotenv
import pandas as pd 
import alpaca_trade_api as tradeapi
from prophet import Prophet
import os
from pathlib import Path
from pandas.tseries.offsets import DateOffset
import datetime as dt
from prophet import Prophet
import hvplot.pandas

ImportError: cannot import name 'Prophet' from 'prophet' (/Users/bahaaamour/Desktop/Baha/prophet.py)

In [ ]:
from dotenv import load_dotenv
import pandas as pd 
import alpaca_trade_api as tradeapi
from prophet import Prophet
import os
from pathlib import Path
from pandas.tseries.offsets import DateOffset
import datetime as dt
from prophet import Prophet
import hvplot.pandas


#working on ALPACA api's
alpaca_api_key = os.getenv("ALPACA_API_KEY")
alpaca_secret_key = os.getenv("ALPACA_SECRET_KEY")

alpaca = tradeapi.REST(
    alpaca_api_key,
    alpaca_secret_key,
    api_version = "v2"
)



# Creating a start date, and TimeFrame
today = dt.date.today()
start = today - DateOffset(years=5)

start_date = start.date()
end_date = today.isoformat()
timeframe = "1Day"



# initializing the alpaca
tickers = ["AAPL", "TSLA", "MSFT"] #this will be gathered from sidebar eventually
tickers_dfs = []

df_portfolio_year = alpaca.get_bars(
    tickers,
    timeframe,
    start = start_date
).df

df_portfolio_year.index=pd.to_datetime(df_portfolio_year.index).date

# Initializing facebook prophet library
def forecast_next_day(ticker):
        stock_df = pd.DataFrame(df_portfolio_year.loc[df_portfolio_year["symbol"] == ticker]["close"])
        stock_df = stock_df.reset_index().rename(columns={"index": "ds", "close": "y"})
        model = Prophet()
        model.fit(stock_df)
        future = model.make_future_dataframe(periods=1, freq="D")
        forecast = model.predict(future)
        forecast_yhats= forecast[["yhat","yhat_lower","yhat_upper"]].tail(1).values[0]
        return forecast_yhats


#Calling the def fubction
forecast_next_day("AAPL")

In [4]:
load_dotenv()

True

In [5]:
alpaca_api_key = os.getenv("ALPACA_API_KEY")
alpaca_secret_key = os.getenv("ALPACA_SECRET_KEY")

type(alpaca_api_key)

str

In [6]:
alpaca = tradeapi.REST(
    alpaca_api_key,
    alpaca_secret_key,
    api_version = "v2"
)

In [7]:
today = dt.date.today()
start = today - DateOffset(years=5)

start_date = start.date()
end_date = today.isoformat()
timeframe = "1Day"

print(start_date, end_date)

2018-03-25 2023-03-25

In [8]:
tickers = ["AAPL", "TSLA", "MSFT"] #this will be gathered from sidebar eventually
tickers_dfs = []

df_portfolio_year = alpaca.get_bars(
    tickers,
    timeframe,
    start = start_date
).df

df_portfolio_year.index=pd.to_datetime(df_portfolio_year.index).date

df_portfolio_year

,open,high,low,close,volume,trade_count,vwap,symbol
2018-03-26,168.060,173.10,166.44,172.77,37541736,232077,170.050591,AAPL
2018-03-27,173.680,175.15,166.92,168.34,40923385,276951,171.395108,AAPL
2018-03-28,167.250,170.02,165.19,166.48,43734295,305622,167.231728,AAPL
2018-03-29,167.805,171.75,166.90,167.78,38572074,219101,169.158209,AAPL
2018-04-02,167.880,168.94,164.47,166.68,37696719,291911,166.360883,AAPL
...,...,...,...,...,...,...,...,...
2023-03-20,178.080,186.44,176.35,183.25,130154197,1180945,182.886435,TSLA
2023-03-21,188.280,198.00,188.04,197.58,153558824,1459451,193.694854,TSLA
2023-03-22,199.300,200.66,190.95,191.15,150657949,1429013,196.690190,TSLA
2023-03-23,195.260,199.31,188.65,192.22,144235875,1324622,194.651032,TSLA
2023-03-24,191.650,192.36,187.15,190.41,116167280,1089613,189.548090,TSLA

In [11]:
#userinput = input("ticker?")
def forecast_next_day(ticker):
        stock_df = pd.DataFrame(df_portfolio_year.loc[df_portfolio_year["symbol"] == ticker]["close"])
        stock_df = stock_df.reset_index().rename(columns={"index": "ds", "close": "y"})
        model = Prophet()
        model.fit(stock_df)
        future = model.make_future_dataframe(periods=7, freq="D")
        forecast = model.predict(future)
        forecast_yhats= forecast[["yhat","yhat_lower","yhat_upper"]].tail(1).values[0]
        return forecast

In [12]:
forecast_next_day("AAPL")

INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:cmdstanpy:start chain 1
INFO:cmdstanpy:finish chain 1

,ds,trend,yhat_lower,yhat_upper,trend_lower,trend_upper,additive_terms,additive_terms_lower,additive_terms_upper,weekly,weekly_lower,weekly_upper,yearly,yearly_lower,yearly_upper,multiplicative_terms,multiplicative_terms_lower,multiplicative_terms_upper,yhat
0,2018-03-26,183.676256,134.080373,221.277255,183.676256,183.676256,-6.897711,-6.897711,-6.897711,2.744191,2.744191,2.744191,-9.641902,-9.641902,-9.641902,0.0,0.0,0.0,176.778544
1,2018-03-27,183.688402,134.454444,219.466502,183.688402,183.688402,-6.872746,-6.872746,-6.872746,2.785297,2.785297,2.785297,-9.658043,-9.658043,-9.658043,0.0,0.0,0.0,176.815656
2,2018-03-28,183.700547,137.837625,220.966535,183.700547,183.700547,-6.525768,-6.525768,-6.525768,3.171941,3.171941,3.171941,-9.697709,-9.697709,-9.697709,0.0,0.0,0.0,177.174779
3,2018-03-29,183.712693,130.532936,221.497061,183.712693,183.712693,-6.567421,-6.567421,-6.567421,3.191485,3.191485,3.191485,-9.758905,-9.758905,-9.758905,0.0,0.0,0.0,177.145272
4,2018-04-02,183.761276,133.555068,221.129684,183.761276,183.761276,-7.390331,-7.390331,-7.390331,2.744191,2.744191,2.744191,-10.134521,-10.134521,-10.134521,0.0,0.0,0.0,176.370945
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1261,2023-03-27,142.524786,91.964157,176.447319,142.524786,142.524786,-6.907565,-6.907565,-6.907565,2.744191,2.744191,2.744191,-9.651756,-9.651756,-9.651756,0.0,0.0,0.0,135.617221
1262,2023-03-28,142.491476,90.175084,176.635541,142.491476,142.491476,-6.900375,-6.900375,-6.900375,2.785297,2.785297,2.785297,-9.685672,-9.685672,-9.685672,0.0,0.0,0.0,135.591101
1263,2023-03-29,142.458166,94.697825,180.831827,142.458166,142.458166,-6.569808,-6.569808,-6.569808,3.171941,3.171941,3.171941,-9.741750,-9.741750,-9.741750,0.0,0.0,0.0,135.888358
1264,2023-03-30,142.424856,91.955585,181.233781,142.424856,142.424856,-6.625472,-6.625472,-6.625472,3.191485,3.191485,3.191485,-9.816957,-9.816957,-9.816957,0.0,0.0,0.0,135.799383
1265,2023-03-31,142.391545,94.542365,179.444243,142.391545,142.391545,-6.959463,-6.959463,-6.959463,2.947536,2.947536,2.947536,-9.906999,-9.906999,-9.906999,0.0,0.0,0.0,135.432082

In [ ]:
def forecast_loop_next_day(ticker):
forecasts = pd.DataFrame(columns=["Ticker", "Forecast"])
    for ticker in tickers:
        stock_df = pd.DataFrame(df_portfolio_year.loc[df_portfolio_year["symbol"] == ticker]["close"])
        stock_df = stock_df.reset_index().rename(columns={"index": "ds", "close": "y"})
        model = Prophet()
        model.fit(stock_df)
        future = model.make_future_dataframe(periods=1, freq="D")
        forecast = model.predict(future)
        forecast_yhats= forecast[["yhat","yhat_lower","yhat_upper"]].tail(1).values[0]
        return forecast_yhats